permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Clean your life"
  description:
    Soapify belives in creating a clean world. We create all our soap by hand, making a more eco-friendly way of making soap. Soapify also donates 20% of our income to Global warming.org. Clean mind, clean world.
  font_url: "https://fonts.google.com/?query=Robo&selection.family=Roboto:300,400,400i,700,900"
  colors:
    patterns:
      brand.logos: "--color-primary"
      buttons.button-white: "--color-accent"
      buttons.basic-button: "--color-primary"
      cards: "--color-primary"
      cards.mission-cards: "--color-secondary"
