patterns:
  mission-cards:
    width: 1000
    title: "Banner card"
    description: |
      These three cards will be used as a description of the banner on the main page, under our mission section.
  image:
    title: "Products page card set"
    description: |
      This set of cards will be used only for the products page.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
  image-card-tilted:
    title: "simple image, just incase"
    description: |
      This card is a simple image of the product. It's only used within the areas that the product shows up titled, unless you find you need it for something else.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: product
